#!/bin/bash

get_current_date (){
	echo $(date '+%Y-%m-%d %H:%M:%S')
}

echo "--------------- push 开始执行[$(get_current_date)] ----------------"
shellDir=$(dirname $0)
cd "$shellDir"

git add *
git add .*
git commit -m "自动同步..."
git push -f

echo -e "--------------- push 执行结束时间[$(get_current_date)] ----------------\n.\n"