#!/bin/bash

get_current_date (){
	echo $(date '+%Y-%m-%d %H:%M:%S')
}

echo "--------------- pull开始执行[$(get_current_date)] ----------------"
shellDir=$(dirname $0)
cd "$shellDir"

git pull

echo -e "--------------- pull执行结束时间[$(get_current_date)] ----------------\n.\n"