#!/bin/bash

get_current_date (){
	echo $(date '+%Y-%m-%d %H:%M:%S')
}


echo "--------------- ⏬⏬⏬⏬⏬ pull 开始执行[$(get_current_date)] ⏬⏬⏬⏬⏬ ----------------"
echo "---------------  before pull; git stash push ----------------"
git stash push


shellDir=$(dirname $0)
cd "$shellDir"

git pull

echo -e "--------------- ⏬⏬⏬⏬⏬ pull 执行结束时间[$(get_current_date)] ⏬⏬⏬⏬⏬ ----------------\n.\n"
echo "---------------  after pull; git stash pop ----------------"
git stash pop