#!/bin/bash
# 同步log

get_current_date (){
	echo $(date '+%Y-%m-%d %H:%M:%S')
}


shellDir=$(dirname $0)
cd "$shellDir"

git status

git add *
git add ../*.log
git add ../../*
# git commit -m  --amend "自动同步(push)[at $(get_current_date)]"
git commit -m "同步日志(push)[at $(get_current_date)]"
git push -f
